### ISSUE TITLE
how to bind json object to value of ngModel

### ISSUE THREAD

**Issue by apriyadarshi38** [formly-js/ng-formly#370]
hii
i want to set [model] in formly to a json which a value of a input field corresponds to a object rather than a string value.

for example

 self.formModel[settingItem.Key] =     {
                            'Value': settingItem.Value,
                            'rid': settingItem['@rid']
                        };

and applied [model]= self.formModel.keyName

**Comment by franzeal** [comment]
Not entirely clear what you're after.  What's the type of the input field?  Can you create an plunker to demonstrate in Angular what you're trying to do (without trying to do it in formly)?

At worst you could create a custom control component that implements ControlValueAccessor and then a custom field component that integrates your custom control with formly.

Guide to implementing [ControlValueAccessor](https://angular.io/docs/ts/latest/api/forms/index/ControlValueAccessor-interface.html):
https://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html

You can create a custom field component exactly like you see in the ui-bootstrap module (instead of binding formControl to input, you would bind the formControl to your custom control component):
https://github.com/formly-js/ng-formly/blob/master/src/ui-bootstrap/types/input.ts#L7

**Comment by apriyadarshi38** [comment]
Thanks for the response,I want to know how can i implement "valueProp" 
For Ex:
{
  key: 'roles',
  type: 'input',
  templateOptions: {
    label: 'Roles',
    options: {id: 1, title : "Administrator"},
    **valueProp**: 'id',
    **labelProp:** 'title'
  }
}

the above options are supported in "angular-formly" but don't know how to implement it in ng2-formly.

**Comment by franzeal** [comment]
The only built-in types I'm aware of that use `labelProp`/`valueProp` are the select type:
https://github.com/formly-js/ng-formly/blob/master/src/ui-bootstrap/types/select.ts#L34

This is similar to angular-formly ([example](http://angular-formly.com/#/example/bootstrap-formly/select)):
https://github.com/formly-js/angular-formly-templates-bootstrap/blob/master/src/types/select.js#L26

Neither library's built-in (bootstrap) input type uses `labelProp`/`valueProp`.
