### ISSUE TITLE
[v2][build] follow Angular Package Format

### ISSUE THREAD

**Issue by aitboudad** [formly-js/ng-formly#459]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview

**Comment by aitboudad** [comment]
we will use https://github.com/dherges/ng-packagr

**Comment by DDeis** [comment]
Hi @aitboudad, any update on this? 
I'm trying to make my own library with **ng-formly** as a dependency to share my custom types between projects, but building the lib with ng-packagr fails, maybe because ng-formly doesn't follow _Angular Package Format_ yet ?

I can try to make a PR to use **ng-packagr** to build **ng-formly** if needed.

**Comment by aitboudad** [comment]
not yet but already done on my local but right now you can use `@ng-formly/core` which follow Angular Package Format

**Comment by DDeis** [comment]
Many thanks sir, It works much better with it! I didn't knew that `@ng-formly/core` was available :)

**Comment by aitboudad** [comment]
the package name might change in the future :), see https://github.com/formly-js/ng-formly/issues/466

**Comment by DDeis** [comment]
Yes I saw #466 and was looking forward to it and more generally issues tagged [v2](https://github.com/formly-js/ng-formly/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20v2) :smile:
