### ISSUE TITLE
repeatSection with HTTP requests

### ISSUE THREAD

**Issue by andriy101** [formly-js/ng-formly#469]
hello,

I forked your example plunker, here it is minified version: https://plnkr.co/edit/bQjoEm2E8C6woK6psFo5?p=preview.   it imitates two-steps form, selectbox within repeatSection should be filled via HTTP get request to 'data.json', received data should be assigned to templateOptions.options. 

The problem:   on initial load (2 repeat sections with select boxes) selectbox options are not populated and predefined values, thus. cannot be selected 
`investments: [
        {
          select: 'Sherrye'
        }, {
          select: 'Antionette'
        },
      ]`
It is populated on newly added select boxes. How can I make selects be filled on initial load?

Also, I am using arrow functions in onInit hook which does not have local field's scope (with access to this.to.options). Is there some assistant function to get current element/field (maybe [`getKeyPath()`](https://github.com/formly-js/ng-formly/blob/master/src/core/src/utils.ts#L10) function, along with lodash `_.get()`).

**Comment by franzeal** [comment]
I've updated your plunker:
https://plnkr.co/edit/DjsD7rRbkQYa55XclatJ?p=preview

**Comment by andriy101** [comment]
Thanks for your reply, I would like to stay with arrow functions implementation of ng4 life hooks, do you have an explanations why my original solution does not work on initial load while working for further newly added elements? thanks in advance

**Comment by franzeal** [comment]
When you're modifying `userFields[2].fieldArray.fieldGroup[0]` you're not modifying the reference that's being bound to by the select type.  Fields provided to the repeat section's nested `FormlyForm`'s are cloned, this is why only the new instances receive your options (you've updated only the source of the cloned fields).

Just to demonstrate, I've excluded the options from cloning in the repeat section and maintain the instance when updating it:
https://plnkr.co/edit/FrgBI6RVtCugs9eqStTE?p=preview

That demonstration isn't generic, so if you went that route you'd probably want to update the repeat section's newFields implementation to clone everything except any templateOptions instances.

The reason I didn't use an arrow function is because in doing so you eliminate access to the field component instances, and I'm not aware of an easy way to access it without submitting a PR that would pass it along as a parameter rather than binding it:
https://github.com/formly-js/ng-formly/blob/c7d5384ca73b7f6e3a865e8b2e78021281446d29/src/core/src/templates/field.type.ts#L44

@mohammedzamakhan or @aitboudad may have better insight to offer.

**Comment by franzeal** [comment]
When you're modifying `userFields[2].fieldArray.fieldGroup[0]` you're not modifying the reference that's being bound to by the select type.  Fields provided to the repeat section's nested `FormlyForm`'s are cloned, this is why only the new instances receive your options (you've updated only the source of the cloned fields).

In this plunker, I update the source in addition to the instance referenced by the field:
https://plnkr.co/edit/sxLPRBBzYWSio4A2QhZ8?p=preview
